### Submit a job with a path (POST)
POST http://localhost:5000/ConvertVideo/sample-video.mp4
Content-Type: application/json

###

### Fire-and-forget submit job (PUT)
PUT http://localhost:5000/ConvertVideo/sample-video.mp4
Content-Type: application/json

###

### Submit multiple jobs (POST)
POST http://localhost:5000/ConvertVideo/3
Content-Type: application/json

###

### Get job state (GET)
# Replace {jobId} with an actual jobId GUID returned from a previous request
GET http://localhost:5000/ConvertVideo/{jobId}
Accept: application/json

###

### Cancel a job (DELETE)
# Replace {jobId} with an actual jobId GUID
DELETE http://localhost:5000/ConvertVideo/{jobId}

###

### Retry a job (POST)
# Replace {jobId} with an actual jobId GUID
POST http://localhost:5000/ConvertVideo/{jobId}
Content-Type: application/json

###